import type { AppState, Paper } from "./types";
const seed = (
  id: string,
  title: string,
  authors: string,
  year: number,
  topics: string[],
  accent: Paper["accent"],
  visual: Paper["visual"],
  abstract: string,
  idea: string,
  problem: string,
  mechanism: string,
  evidence: string,
  limitation: string,
): Paper => ({
  id,
  arxivId: id,
  title,
  authors,
  year,
  topics,
  accent,
  visual,
  abstract,
  recall: {
    idea,
    problem,
    mechanism,
    evidence,
    limitation,
    sourceIds: ["abstract"],
    provenance: "editorial",
    evidenceScope: "abstract",
  },
  scene: null,
  sources: [
    {
      id: "abstract",
      label: "Original paper · abstract",
      url: `https://arxiv.org/abs/${id}`,
      excerpt: abstract,
    },
  ],
  generationStatus: "ready",
  createdAt: "2026-09-12T00:00:00Z",
});
export const catalog: Paper[] = [
  seed(
    "2401.04088",
    "Mixtral of Experts",
    "Albert Q. Jiang et al.",
    2024,
    ["Mixture of experts", "Language models"],
    "violet",
    "experts",
    "Mixtral 8x7B uses eight feedforward experts in each layer. A router selects two experts per token and combines their outputs. It has 47B total parameters and 13B active parameters during inference.",
    "More capacity. Only two experts at a time.",
    "How can a language model increase capacity without activating every parameter for every token?",
    "At each layer, a learned router sends each token to two of eight feedforward experts. Their outputs are combined.",
    "The paper reports 47B total parameters with 13B active per token and strong results on its evaluated benchmarks.",
    "Sparse activation does not mean the whole model fits in the memory needed for only its active parameters.",
  ),
  seed(
    "2106.09685",
    "LoRA: Low-Rank Adaptation of Large Language Models",
    "Edward J. Hu et al.",
    2021,
    ["Efficient adaptation", "Low-rank methods"],
    "sage",
    "lora",
    "LoRA freezes pretrained model weights and injects trainable rank decomposition matrices into Transformer layers, reducing trainable parameters for downstream adaptation.",
    "Keep the model. Learn a small update.",
    "Full fine-tuning creates an expensive copy of all model parameters for each task.",
    "Freeze the original weight matrix and train two smaller matrices whose product supplies a low-rank update.",
    "The paper reports competitive quality with full fine-tuning on its studied models, with fewer trainable parameters.",
    "The best rank and target layers depend on the task. A low-rank update is a constraint, not a guarantee of sufficient capacity.",
  ),
  seed(
    "1706.03762",
    "Attention Is All You Need",
    "Ashish Vaswani et al.",
    2017,
    ["Attention", "Foundations"],
    "blue",
    "attention",
    "The Transformer is a sequence transduction model based solely on attention mechanisms, dispensing with recurrence and convolutions.",
    "Let each token find the context it needs.",
    "Recurrent sequence models process dependencies through a chain of hidden states.",
    "Attention compares queries with keys, normalizes the scores, and uses them to mix values into a contextual representation.",
    "The paper evaluates the Transformer on translation tasks and reports strong quality with substantially parallelizable training.",
    "Attention alone does not encode token order. Position information is supplied separately.",
  ),
  seed(
    "2103.00020",
    "Learning Transferable Visual Models From Natural Language Supervision",
    "Alec Radford et al.",
    2021,
    ["Multimodal learning", "Contrastive learning"],
    "ochre",
    "contrastive",
    "CLIP trains image and text encoders jointly to predict which caption goes with which image, using 400 million image-text pairs.",
    "Teach images and words to meet in the same space.",
    "Fixed image-classification labels restrict the visual concepts a model can learn and transfer.",
    "Contrastive training brings matched image–text representations closer while distinguishing them from other pairs in the batch.",
    "The paper evaluates transfer to many vision datasets using natural-language class descriptions.",
    "Transfer quality varies across tasks, and the learned representations inherit biases and gaps in their training data.",
  ),
  seed(
    "1803.03635",
    "The Lottery Ticket Hypothesis",
    "Jonathan Frankle & Michael Carbin",
    2019,
    ["Pruning", "Efficient training"],
    "violet",
    "pruning",
    "Dense randomly initialized networks contain subnetworks that, when trained in isolation, can reach test accuracy comparable to the original network in a similar number of iterations.",
    "The connections matter. So do their starting values.",
    "A pruned network may be small, but training that architecture from scratch can be difficult.",
    "Train a dense network, prune connections, reset surviving weights to their original initialization, then train the resulting subnetwork.",
    "The authors demonstrate trainable subnetworks in the feedforward image-classification settings they study.",
    "Finding a ticket requires training and pruning. This does not automatically provide cheap training or hardware-efficient sparse execution.",
  ),
  seed(
    "2312.00752",
    "Mamba: Linear-Time Sequence Modeling with Selective State Spaces",
    "Albert Gu & Tri Dao",
    2023,
    ["State space models", "Sequence modeling"],
    "blue",
    "memory",
    "Mamba introduces input-dependent selection into state space models, allowing a model to selectively propagate or forget information along the sequence.",
    "A bounded memory that chooses what survives.",
    "Fixed state-space dynamics have difficulty selecting important content in discrete sequences.",
    "Let the input change the state update so the recurrent state can selectively retain or replace information.",
    "The paper evaluates selective state-space models across language, audio and genomics, with linear sequence-length scaling.",
    "A fixed-size state compresses history; it does not expose an unrestricted cache of all earlier tokens.",
  ),
];
export function initialState(): AppState {
  return {
    schemaVersion: 2,
    papers: structuredClone(catalog),
    entries: {},
    direction: { goal: "", questions: "", topics: [] },
    recommendations: [
      {
        paperId: "2401.04088",
        role: "Explore a mechanism",
        reason:
          "A concrete introduction to how sparse expert routing separates model capacity from per-token computation.",
        focus:
          "The router and the distinction between total and active parameters.",
        depth: "Start with the architecture",
      },
      {
        paperId: "2106.09685",
        role: "Build a foundation",
        reason:
          "A compact mechanism for understanding parameter-efficient adaptation and the role of low-rank updates.",
        focus: "The frozen weight matrix and the trainable update.",
        depth: "Read the method",
      },
      {
        paperId: "2103.00020",
        role: "Connect two ideas",
        reason:
          "A useful bridge from language models to visual representations and contrastive objectives.",
        focus: "How matched and mismatched pairs shape a shared space.",
        depth: "Study the training objective",
      },
    ],
    recommendationSource: "starter",
    recommendedAt: null,
    feedback: [],
    jobs: [],
    workerSeenAt: null,
    onboardingDone: false,
  };
}
