import {readFile,writeFile,readdir,mkdir,rename,stat} from "node:fs/promises";
import path from "node:path";
import {createHash} from "node:crypto";
import {z} from "zod";
import {subjectLessonSchema,subjectPublicLessonSchema,subjectFigureSchema,validateSubjectLesson,type SubjectLesson,type PublishedLesson} from "../src/lib/subjects";
import {validateSubjectMath} from "../src/lib/subject-math";
import {subjectPatchSchema,applySubjectPatch} from "../src/lib/subject-repair";
import {publishSubjectLesson,subjectPublicationDigest} from "../src/lib/subject-publication";
import {experimentContracts,onlineAttention,volumeRendering,smoothQuantScaling,rollingCausalWindow} from "../src/lib/subject-experiments";
import {importPaper} from "../src/lib/papers";
import {researchSources} from "../worker/sources";
import {subjectModel} from "../worker/subject-model";
import {selectSubjectEvidence} from "../worker/subject-evidence";
import {SOURCE_EXTRACTION_VERSION,hasSubstantiveSourceBody} from "../src/lib/source-extraction";

const targets={
  "mistral":{figureId:"fig-memory",kind:"rolling-window",sectionId:"s4",instructions:"Replace the unrelated allocation-padding illustration with the tested rolling-window cache instance in s4. Preserve existing c5/c8 and primary section2 formulas: inclusive reads i-W..i and cache mapping slot(i)=i mod W. The constructed example fixes W=4 cached previous tokens and holds the current local K/V separately. Declare its sequential convention naturally: queryi first reads cached positions max(0,i-4)..i-1 plus currenti, then writesi intoi mod4, overwritingi-4 after that read. Atdefaulti5, before slots are [4,1,2,3], eligible [1,2,3,4,5], writeslot1 replaces1, after slots [4,5,2,3]. Show why logical identity differs from physicalslot and future positions remainineligible. Do not silently collapse the paper inclusive formula to fourtotal positions or claim this illustrative read-before-write order is verifiedMistral runtime. Remove old 9-token/16-slot padding prose. Correct any affected window/cache wording in s2/s3/s4; keep real empirical memory and quality findings in their existing source-qualified context. This numerical instance has no learned attention weights, GQA, chunked prefill or multilayer reach simulation; teach those actual methods from their source-supported prose without attributing them to this control. Update quiz only if it depends on the obsolete allocation example."},
  "smoothquant":{figureId:"f2",kind:"paired-scaling",sectionId:"s3",instructions:"Replace unrelated offset standardization with SmoothQuant actual paired channel scaling in s3, supported by existing c6/c8/c9 and primary section4 equations3/4. Keep claim identities and all correct empirical conclusions. Teach Xhat=X diag(s)^(-1), What=diag(s)W, and s_j=a_j^alpha/b_j^(1-alpha), with a/b the activation-column/weight-row absolute maxima. Use the exact constructed matrices/colors-independent numeric inputs and output from the contract: X=[[8,2,-1],[-4,1,0.5]], W=[[0.5,-0.25],[1,0.5],[-1,0.5]], Y=[[7,-1.5],[-1.5,1.75]]. Compute the alpha=.5 case s=[4,sqrt(2),1] and maxima [2,sqrt(2),1] for both transformed sides. Explain the alpha0/1 extremes and how channel scales cancel in every dot product while transferring range. Remove the obsolete standardization analogy and offset-control explanation. The control performs exact unquantized paired scaling, so keep actual INT8 rounding, reported accuracy/latency, and calibration results in their supported evidence sections rather than treating these constructed values as measurements. Explain chosen assumptions naturally in the lesson; update quiz only if needed for the changed example."},
  "nerf-representing-scenes-as-neural-radiance":{figureId:"fig-spatial",kind:"volume-rendering",sectionId:"s3",instructions:"Replace the unrelated Gaussian-footprint example in s2 with the actual NeRF finite-ray visibility recurrence placed in s3. Restore s2 to supported field/position material without the Gaussian analogy. Preserve the primary c3/c4 claims and other correct explanations. Teach alpha_i=1-exp(-sigma_i delta_i), T1=1, w_i=T_i alpha_i, and Tnext=T_i(1-alpha_i). Define symbols and compute an original four-interval delta=1 example at the default front density1 using the exact fixed colors and other densities in the contract. State naturally that these are constructed intervals and color choices, with a white background weighted by residual T5 after the finite ray. Explain why increasing only sigma1 raises its weight and reduces every later/background contribution while positions and colors remain fixed. Keep existing supported positional-encoding, hierarchical sampling, field architecture and learning explanations. This figure demonstrates the compositing recurrence rather than predicting a learned field, changing sampling, or reporting image quality. Update quiz only if needed for the replaced example."},
  "flashattention-fast-and-memory-efficient-exact":{figureId:"f2",kind:"streaming-attention",sectionId:"s4",instructions:"Replace the unrelated KV allocation analogy with the actual online softmax mechanism. Place it in s4, moving the old f2 reference away from s3. Teach the maximum m, normalizer ell and weighted value accumulator u; show one correctly calculated two-tile example for the exact fixed scores and values in the contract. Explain why reverse tile order changes intermediate maximum/rescaling but preserves the final result. Keep hardware/IO claims tied to their original conditions; one row is a small arithmetic instance of the recurrence, not a memory-traffic benchmark. Remove the obsolete slot-allocation discussion from s3."},
  "geometry-of-noise":{figureId:"fig-noise",kind:"noise-shells",sectionId:"s1",instructions:"Replace the first norm histogram with an original rotatable 3D shell geometry example. Explain in s1 that D=3,d=0 and one point is at the origin; radius sqrt(E[||epsilon||²])=sigma sqrt(3), giving 0.4sqrt(3)≈0.693 and sqrt(3)≈1.732. These surfaces mark RMS radii; actual D=3 Gaussian draws vary around them and can overlap. They do not prove posterior concentration or high-dimensional shell disjointness. Explain how increasing codimension later changes relative radial concentration, with actual source-supported assumptions. Rotation changes the view only, visibility does not resample or change sigma, and the inner-sigma slider moves the inner RMS radius."},
}as const;
const hash=(text:string)=>createHash("sha256").update(text).digest("hex");
const checkSchema=z.object({science:z.object({passed:z.boolean(),findings:z.array(z.string()).max(12)}),teaching:z.object({passed:z.boolean(),findings:z.array(z.string()).max(12)}),experiments:z.object({passed:z.boolean(),findings:z.array(z.string()).max(12)}),quiz:z.object({passed:z.boolean(),findings:z.array(z.string()).max(12)})});

async function main(){
  const id=process.argv[process.argv.indexOf("--id")+1] as keyof typeof targets;
  const target=targets[id];if(!target)throw new Error("Only explicitly authorized Mistral, SmoothQuant, NeRF, FlashAttention and Geometry figure refinements are supported");
  const file=path.resolve("src/content/subjects/lessons",id+".json");
  const originalBytes=await readFile(file,"utf8");
  const original=JSON.parse(originalBytes)as PublishedLesson;
  const content=subjectPublicLessonSchema.parse(original);
  if(subjectPublicationDigest(content,original)!==original.review.contentDigest)throw new Error("Stale lesson fingerprint");
  const privateBase=path.resolve(".artifacts/subjects",id),directory=path.join(privateBase,"figure-refinement");await mkdir(directory,{recursive:true});
  const candidates=(await Promise.all((await readdir(privateBase)).filter(name=>/^(?:draft|recovery)-\d+(?:-candidate)?\.json$/.test(name)).map(async name=>{
    try{return {data:subjectLessonSchema.parse(JSON.parse(await readFile(path.join(privateBase,name),"utf8"))),modified:(await stat(path.join(privateBase,name))).mtimeMs};}catch{return null;}
  }))).filter(candidate=>candidate!==null).sort((a,b)=>b.modified-a.modified);
  const ledger=candidates.find(candidate=>JSON.stringify(candidate.data.claims.map(({evidence,...claim})=>claim))===JSON.stringify(content.claims));
  if(!ledger)throw new Error("Matching private audited ledger unavailable");
  let lesson:SubjectLesson=subjectLessonSchema.parse({...content,claims:content.claims.map(claim=>({...claim,evidence:ledger.data.claims.find(privateClaim=>privateClaim.id===claim.id)!.evidence}))});
  const catalog=JSON.parse(await readFile("src/content/subjects/catalog.json","utf8"));const entry=catalog.entries.find((item:{id:string})=>item.id===id);if(!entry)throw new Error("Catalog identity missing");
  const paper=await importPaper(entry.arxivId),extracted=await researchSources(paper);
  if(extracted.scope!=="full-text"||!hasSubstantiveSourceBody(extracted.sources))throw new Error("Full primary evidence required");
  const context={paper:{id:paper.id,title:paper.title},scope:extracted.scope,extractionVersion:SOURCE_EXTRACTION_VERSION,capturedAt:new Date().toISOString(),sources:extracted.sources};
  await writeFile(path.join(directory,"evidence.json"),JSON.stringify(context,null,2));
  validateSubjectLesson(lesson,extracted.sources);validateSubjectMath(lesson);
  const sectionIds=lesson.sections.map(section=>section.id)as[string,...string[]],sourceIds=extracted.sources.map(source=>source.id)as[string,...string[]];
  const refinementSchema=z.object({
    figure:subjectFigureSchema.extend({id:z.literal(target.figureId),kind:z.literal(target.kind)}),
    sections:z.array(z.object({id:z.enum(sectionIds),title:z.string().min(5).max(100),markdown:z.string().min(400).max(10000),sourceIds:z.array(z.enum(sourceIds)).min(1).max(8),claimIds:z.array(z.enum(lesson.claims.map(claim=>claim.id)as[string,...string[]])).min(1).max(8)})).min(1).max(4),
    quiz:subjectLessonSchema.shape.quiz.nullable(),
  });
  const common="\nPRIMARY EVIDENCE:\n"+JSON.stringify(context)+"\nEXACT EXPERIMENT CONTRACTS:\n"+JSON.stringify(experimentContracts)+"\nNUMERIC REFERENCE FOR STREAMING:\n"+JSON.stringify({forward:onlineAttention(2),reverse:onlineAttention(2,"reverse")})+"\nNUMERIC REFERENCE FOR VOLUME RENDERING:\n"+JSON.stringify({default:volumeRendering(1),clear:volumeRendering(0),dense:volumeRendering(4)})+"\nNUMERIC REFERENCE FOR PAIRED SCALING:\n"+JSON.stringify({alpha0:smoothQuantScaling(0),alphaHalf:smoothQuantScaling(.5),alpha1:smoothQuantScaling(1)})+"\nNUMERIC REFERENCE FOR ROLLING WINDOW:\n"+JSON.stringify({start:rollingCausalWindow(0),firstOverwrite:rollingCausalWindow(4),default:rollingCausalWindow(5),last:rollingCausalWindow(11)});
  const refinement=await subjectModel(`Improve only this lesson's explicitly requested figure and directly related teaching prose. ${target.instructions} Return the new figure and complete replacement sections that need changes, retaining all correct explanations. Keep claim identities and source support intact; derivations and tiny arithmetic examples may be general consequences of the cited equations. Define symbols, use correct KaTeX, and mark chosen toy inputs naturally as illustrative in the lesson itself. Avoid standalone warnings and repetitive captions; the actual assumptions/interpretation belong in the teaching prose. Return quiz=null unless a question must change due to the updated computation, then preserve three questions with all choice explanations.\nLESSON:\n${JSON.stringify(lesson)}${common}`,refinementSchema,directory,"refinement");
  lesson.figures=lesson.figures.map(figure=>figure.id===target.figureId?refinement.figure:figure);
  lesson.sections=lesson.sections.map(section=>({...section,figureId:section.figureId===target.figureId?null:section.figureId}));
  const placement=lesson.sections.find(section=>section.id===target.sectionId)!;
  if(placement.figureId!==null)throw new Error("Requested figure placement conflicts with an existing figure");placement.figureId=target.figureId;
  const seen=new Set<string>();
  for(const update of refinement.sections){if(seen.has(update.id))throw new Error("Duplicate section update");seen.add(update.id);Object.assign(lesson.sections.find(section=>section.id===update.id)!,update);}
  if(refinement.quiz!==null)lesson.quiz=refinement.quiz;
  let findings="",evidenceSignature=hash(JSON.stringify(lesson.claims.map(({evidence,...claim})=>claim)));
  for(let attempt=0;attempt<5;attempt++){
    try{
      if(attempt){const patch=await subjectModel(`Repair only these defects in the updated original lesson. Preserve the explicitly requested figure kind, identities, and all correct content. Use complete field replacements with exact schema bounds and only supplied primary citation IDs. Do not generate quoted evidence; changed claims and citations receive exact primary passage selection separately. Explain each computation in the prose without repetitive warning blocks.\nFINDINGS:\n${findings}\nLESSON:\n${JSON.stringify(lesson)}${common}`,subjectPatchSchema(lesson,sourceIds,{allowEvidenceUpdates:false,allowClaimLinks:true}),directory,`patch-${attempt}`);lesson=applySubjectPatch(lesson,patch,sourceIds);}
      const signature=hash(JSON.stringify(lesson.claims.map(({evidence,...claim})=>claim)));
      if(signature!==evidenceSignature){lesson=await selectSubjectEvidence(lesson,extracted.sources,directory,`evidence-${attempt}`);evidenceSignature=signature;}
      await writeFile(path.join(directory,`candidate-${attempt}.json`),JSON.stringify(lesson,null,2));
      validateSubjectLesson(lesson,extracted.sources);validateSubjectMath(lesson);
      const review=await subjectModel(`Independently audit every load-bearing claim, equation, tiny calculation and quiz choice against the supplied primary evidence. Check that the replacement figure accurately teaches the actual paper mechanism or declared geometric instance using the EXACT implemented contract, including changed controls and display values. FlashAttention must carry maximum, normalizer and weighted accumulator correctly and preserve dense attention for either tile order. The shell figure is an ideal RMS-radius 3D point example, not actual Gaussian draws or a claim of D=3 concentration. The NeRF figure must exactly compose the four constructed unit-length intervals and their residual white-background term; only front density changes, with fixed sample geometry/colors and no learned-field or sampling claim. SmoothQuant must divide activation columns and multiply matching weight rows by the same positive channel scales, preserving the displayed exact matrix product while changing ranges. Check the extrema and alpha=.5 arithmetic against the numeric reference; it performs no quantization or measured calibration. Mistral must retain its source inclusive i-W..i formula and moduloW slot mapping. The illustrative four-slot instance reads four cached previous states plus its separate currentlocal state before the modulo write; the prose must declare that convention without claimingverified runtimeorder or silently converting W to fourtotaleligible positions. Verify before/after logical identities, actual eviction and futureineligibility against the reference. Check that the prose explains these distinctions naturally; do not require repeated caption/disclaimer blocks. Reject unsupported source claims, missing definitions, wrong numerical results, mismatched controls, or quiz answers relying on removed examples. Each check passes only with zero substantive findings.\nLESSON:\n${JSON.stringify(lesson)}${common}`,checkSchema,directory,`review-${attempt}`);
      const checks=Object.values(review);findings=checks.flatMap(check=>check.findings.length?check.findings:check.passed?[]:["Review failed without a finding"]).join("\n");
      if(checks.some(check=>!check.passed||check.findings.length))throw new Error(findings);
      const published=publishSubjectLesson(lesson,{id,createdAt:original.createdAt,pipelineVersion:original.pipelineVersion,sources:extracted.sources.map(source=>({id:source.id,label:source.label,url:source.url,digest:hash(source.excerpt),extractionVersion:context.extractionVersion,capturedAt:context.capturedAt}))});
      if(await readFile(file,"utf8")!==originalBytes)throw new Error("Parent lesson changed during refinement; publication aborted");
      await writeFile(file+".tmp",JSON.stringify(published,null,2)+"\n");await rename(file+".tmp",file);
      console.log(`PASSED ${id}: ${target.kind}; ${published.review.contentDigest}`);return;
    }catch(error){findings=(error as Error).message;await writeFile(path.join(directory,`defects-${attempt}.json`),JSON.stringify({at:new Date().toISOString(),error:findings}));console.log(`REPAIR ${id} ${attempt+1}: ${findings.slice(0,220)}`);}
  }
  throw new Error("Figure refinement exhausted four repairs; existing reviewed lesson retained");
}
main().catch(error=>{console.error((error as Error).message);process.exitCode=1;});
